### ISSUE TITLE
How deep the dereferencing goes

### ISSUE THREAD

**Issue by ejalal** [cvent/json-schema-deref#25]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
0.3.5

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
v6.10.2 on Linux (Centos)

3) Sample source code or steps to reproduce
var deref = require('json-schema-deref');
var myschema = require('./schema.json');

deref(myschema, function(err, fullSchema) {
  console.dir(fullSchema); // has the full expanded $refs
});

Hi,
Is there a parameter to specify how deep the dereferencing goes ?
If looks like only the top level schemas are resolved, well the ones referenced in my original schema. If the resolved schemas on the first level contain other references, they are not resolved. All schemas are in the same folder.
Thanks for your help.

**Comment by bojand** [comment]
Hello, there should not be a limit on how deep the schema deref goes. Can you provide a sample schema that is exhibiting the issue? For example the following test schemas all have somewhat relatively deep `$ref`'s and work:

https://github.com/bojand/json-schema-deref/blob/master/test/schemas/api.links.json
https://github.com/bojand/json-schema-deref/blob/master/test/schemas/app.json
https://github.com/bojand/json-schema-deref/blob/master/test/schemas/issue12.json

**Comment by ejalal** [comment]
The console.dir(fullSchema) was a bit misleading, because it was displaying [Object] in some elements which I interpreted as an error finding the schema.
I replaced it with console.log(JSON.stringify(fullSchema)) and all is OK now.
I'm new to this so sorry for the false alarm, and thank for your support.
